namespace Cinteros.Xrm.Plugins.DataUpdateTool
{
    using System.ComponentModel.Composition;
    using Cinteros.Xrm.DataUpdateTool;
    using XrmToolBox.Extensibility;
    using XrmToolBox.Extensibility.Interfaces;

    [Export(typeof(IXrmToolBoxPlugin)),
    ExportMetadata("Name", "Data Update Tool"),
    ExportMetadata("Description", "Tool update or touch single attributes on a set of records"),
    ExportMetadata("SmallImageBase64", "iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNWWFMmUAAAPJSURBVHhe7Zw5i1NRGIYnKsO4pBhHbKK4dDZiExgG41ZZ+QOsVRSmCSIWFsMIgp1VXEaxMGBpof6BcSsFR0jnGBX9AeOKaK7vG3JkknxJ7rm5yznnngeeZibLvQ9Zv3NvJjwezwAK8EJHjyaMdw8GHX1EDXrjKa9D/s8zhEHxlHehjziAbfAxlMKt10cUYLyXUAom+RBuhR6gG0/5COY+YhFGiad8DnMbcR98B6UwOuYy4n74CUpBovgK7oC5IO54yg9wL3Sa4/ArlALEodMRGe8XlHY8ThnxIHSKtOIpv8Mj0AlOwd9Q2tEkdSLiWfgHSjuYhlZHnIctKO1YmjLiGWgVpsRTclvOQ/Mpl8uXS6VSCwaG2ZqbmzM+4vza2lorMJQWmJmZuYPtNHIc1n7aImBnc82kWCzyKb0EjYm4EV6B7dc8SwLSp3ALzBTG6xrBWxSQPoOZRdwM+9YvLAtIM4k4cBBqYUD6Fm6HqTB0imxpQMohxB6YKBxaDh3BWxyQJhqRI/iRg1DLA1JGrMBYCRWPOhCQ8vtzbBEPwI9QuqM+dQKurq4G1Wo1VScnJ8XtFowl4lH4E0p3IKoTsNFoiLdhkIx4GkZCOx51LKDyHNTiJPwBpRsbqqMBaeiIHPlINxBKhwPSkRHHikcdD0g5DhO5BqUraJmDgLQvIv8gXVDbnASkbNYeQlQ7f4jFHAWkddg+sokjHekC2uYoYBP+/94cW8ScBGSrvqPB+HzmWoF0hdDmIODQASwXWsZ6Q3E84DIcOb1mxBsw0sK4wwEfQC5jhIYfqrUjOhrwNoyEdkQHA96CY8HvfxzrSDfep07AZrMZVCqV1JydnQ0KhYK43YJ/4SUYCxxthYqoEzALQk6kGU97hDUKHmc3MqIDARmPxzUmAiN+gdIdt7U8IA+APwEThUfBc+VK2gCbAzLeYZgKAyNaGjDVeIpdkKdZdW2MhQE/w0MwEziE6IpoWcD3cDfMlK6IFgV8AzOPp2DE+9CWgBwKTEGj2ACXTA84PT1tZDzFVK1WW1lcXAxMtF6vLy8sLBgbT8GPOCtQvdaYotGPvF763p0z1qp4ClMi3oSboJUw4hMo7VgaMp71vzHDHeCP5Ug7mKROxFOkHZFTZGfiKdKIyFneRehcPAV37CqMtOI3wkSmyKYy9mF0PeYqniKuiN+gMz8wocu4ERkv9nM6bOMYDL1sus5cP/J6Cb1s2pHnrfh4PYSNmMpJgbbCs6KGRfTxQsBxmHRqmY+nQW/E13An9GigIr6AnOp4IsBHnY/n8QxgYuIfcGnV4Ve77pMAAAAASUVORK5CYII="), // null for "no logo" image or base64 image content
    ExportMetadata("BigImageBase64", "iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNWWFMmUAAAPJSURBVHhe7Zw5i1NRGIYnKsO4pBhHbKK4dDZiExgG41ZZ+QOsVRSmCSIWFsMIgp1VXEaxMGBpof6BcSsFR0jnGBX9AeOKaK7vG3JkknxJ7rm5yznnngeeZibLvQ9Zv3NvJjwezwAK8EJHjyaMdw8GHX1EDXrjKa9D/s8zhEHxlHehjziAbfAxlMKt10cUYLyXUAom+RBuhR6gG0/5COY+YhFGiad8DnMbcR98B6UwOuYy4n74CUpBovgK7oC5IO54yg9wL3Sa4/ArlALEodMRGe8XlHY8ThnxIHSKtOIpv8Mj0AlOwd9Q2tEkdSLiWfgHSjuYhlZHnIctKO1YmjLiGWgVpsRTclvOQ/Mpl8uXS6VSCwaG2ZqbmzM+4vza2lorMJQWmJmZuYPtNHIc1n7aImBnc82kWCzyKb0EjYm4EV6B7dc8SwLSp3ALzBTG6xrBWxSQPoOZRdwM+9YvLAtIM4k4cBBqYUD6Fm6HqTB0imxpQMohxB6YKBxaDh3BWxyQJhqRI/iRg1DLA1JGrMBYCRWPOhCQ8vtzbBEPwI9QuqM+dQKurq4G1Wo1VScnJ8XtFowl4lH4E0p3IKoTsNFoiLdhkIx4GkZCOx51LKDyHNTiJPwBpRsbqqMBaeiIHPlINxBKhwPSkRHHikcdD0g5DhO5BqUraJmDgLQvIv8gXVDbnASkbNYeQlQ7f4jFHAWkddg+sokjHekC2uYoYBP+/94cW8ScBGSrvqPB+HzmWoF0hdDmIODQASwXWsZ6Q3E84DIcOb1mxBsw0sK4wwEfQC5jhIYfqrUjOhrwNoyEdkQHA96CY8HvfxzrSDfep07AZrMZVCqV1JydnQ0KhYK43YJ/4SUYCxxthYqoEzALQk6kGU97hDUKHmc3MqIDARmPxzUmAiN+gdIdt7U8IA+APwEThUfBc+VK2gCbAzLeYZgKAyNaGjDVeIpdkKdZdW2MhQE/w0MwEziE6IpoWcD3cDfMlK6IFgV8AzOPp2DE+9CWgBwKTEGj2ACXTA84PT1tZDzFVK1WW1lcXAxMtF6vLy8sLBgbT8GPOCtQvdaYotGPvF763p0z1qp4ClMi3oSboJUw4hMo7VgaMp71vzHDHeCP5Ug7mKROxFOkHZFTZGfiKdKIyFneRehcPAV37CqMtOI3wkSmyKYy9mF0PeYqniKuiN+gMz8wocu4ERkv9nM6bOMYDL1sus5cP/J6Cb1s2pHnrfh4PYSNmMpJgbbCs6KGRfTxQsBxmHRqmY+nQW/E13An9GigIr6AnOp4IsBHnY/n8QxgYuIfcGnV4Ve77pMAAAAASUVORK5CYII="), // null for "no logo" image or base64 image content
    ExportMetadata("BackgroundColor", "#ffffff"), // Use a HTML color name
    ExportMetadata("PrimaryFontColor", "#000000"), // Or an hexadecimal code
    ExportMetadata("SecondaryFontColor", "DarkGray")]
    public class VersionVerificationTool : PluginBase
    {
        #region Public Methods

        public override IXrmToolBoxPluginControl GetControl()
        {
            return new MainControl();
        }

        #endregion Public Methods
    }
}